### ISSUE TITLE
NULL pointer dereference is detected

### ISSUE THREAD

**Issue by MicroMilo** [gecarval/ParticleSim#1]
location: `calls.c#L15` function `exit_data`

for example:

if `data->map` is NULL, the `data->map->parsed_file` is NULL pointer derefence

```c
	if (data->map->parsed_file != NULL)
		ft_free_matrix(data->map->parsed_file);
	if (data->map != NULL)
		free(data->map);
```

**Comment by gecarval** [comment]
I appreciate your help, even if is a naive approach this should work!

Before:
> ```c
> 	if (data->map->parsed_file != NULL)
> 		ft_free_matrix(data->map->parsed_file);
> 	if (data->map != NULL)
> 		free(data->map);
> ```

I will verify if all previous pointers exists:
```c
if (data != NULL && data->map != NULL && data->map->parsed_file != NULL)
	ft_free_matrix(data->map->parsed_file);
if (data != NULL && data->map != NULL)
	free(data->map);
```
